In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [4]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [5]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [6]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [7]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [10]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [11]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [12]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])
# Конкатенація вздовж 0-го виміру
result = torch.cat((x, y), dim=0)
print(result)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [14]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])
# Стек вздовж нового виміру (вимір 0)
result = torch.stack((x, y), dim=0)
print(result)

RuntimeError: stack expects each tensor to be equal size, but got [2, 2] at entry 0 and [1, 2] at entry 1

In [18]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
# Стек вздовж нового виміру (вимір 0)
result = torch.stack((x, y), dim=0)
print(result)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [19]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.7220, 0.8217, 0.2612, 0.7375],
        [0.8328, 0.8444, 0.2941, 0.3788]])
tensor([[1.4439, 1.6434, 0.5224, 1.4750],
        [1.6657, 1.6888, 0.5882, 0.7576]])


Правила трансляції:
- Кожен тензор повинен мати принаймні один вимір — ніяких порожніх тензорів.
- Порівняння розмірів двох тензорів від останнього до першого:
    - розміри вимірів мають бути рівними
    або
    - один із вимірів має розмір 1
    або
    - розмірність не існує в одному з тензорів.

In [20]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]]])
tensor([[[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]]])
tensor([[[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]],

        [[0.4762, 0.7242],
         [0.4762, 0.7242],
         [0.4762, 0.7242]]])


In [22]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))
print(agg)
print(tensor)

12.0 <class 'float'>
tensor(12.)
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [23]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [24]:
# Переносимо наш тензор на графічний процесор (GPU), якщо він доступний
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [25]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [29]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)
print(c)

d = c.squeeze(0)
print(d.shape)
print(d)

torch.Size([1, 20])
tensor([[0.4836, 0.1451, 0.7946, 0.4126, 0.1625, 0.9214, 0.2327, 0.5813, 0.7089,
         0.3735, 0.9389, 0.3442, 0.9211, 0.6042, 0.7966, 0.6166, 0.6064, 0.9906,
         0.0350, 0.0411]])
torch.Size([20])
tensor([0.4836, 0.1451, 0.7946, 0.4126, 0.1625, 0.9214, 0.2327, 0.5813, 0.7089,
        0.3735, 0.9389, 0.3442, 0.9211, 0.6042, 0.7966, 0.6166, 0.6064, 0.9906,
        0.0350, 0.0411])
torch.Size([2, 2])
tensor([[0.7051, 0.5522],
        [0.2367, 0.5497]])
torch.Size([2, 2])
tensor([[0.7051, 0.5522],
        [0.2367, 0.5497]])


In [30]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# також може викликати його як метод у модулі torch:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])
